Repository Animeboynz/Mihon-Backup-Viewer, pull requests merged in 2024-07, with the labels that each got.

#70 Implement Search
  .pre-commit-config.yaml
  index.html
  package.json
  scripts/library.js
  scripts/script.js
  styles.css
Labels: Feature to Add

#72 Chapter order button
  index.html
  scripts/script.js
  styles.css
Labels: Ready to Merge

#73 Changes to portrait mode
  index.html
  package.json
  scripts/constants.js
  scripts/library.js
  scripts/materialSymbol.js
  scripts/modals.js
  scripts/script.js
  styles.css
Labels: Enhancement, GUI / Visual, JS / Technical, PR - Ready to Merge

#80 [Chore] Split CSS + Images subfolder
  .esbuild.mjs
  .github/workflows/prettify-commits.yml
  .gitignore
  package-lock.json
  package.json
  site/img/icons/android-chrome-192x192.png
  site/img/icons/android-chrome-512x512.png
  site/img/icons/apple-touch-icon.png
  site/img/icons/favicon-16x16.png
  site/img/icons/favicon-32x32.png
  site/img/icons/site.webmanifest
  site/img/nocover.jpg
  site/index.html
  site/script.js
  site/scripts/library.js
  site/scripts/loadBackup.js
  site/styles.css
  site/styles/library.css
  site/styles/load-backup.css
  site/styles/manga-details.css
  site/styles/modals.css
  site/styles/root.css
  site/styles/settings-modal.css
Labels: Ready to Merge

#83 Unread Filter
  .esbuild.mjs
  site/index.html
  site/script.js
  site/scripts/constants.js
  site/scripts/library.js
  site/scripts/loadBackup.js
  site/scripts/settings.js
Labels: Enhancement, Test & Merge

#77 Add Edit Manga Details Modal
  site/index.html
  site/script.js
  site/scripts/constants.js
  site/scripts/editBackup.js
  site/scripts/library.js
  site/styles.css
  site/styles/edit-modal.css
  site/styles/library.css
Labels: Feature to Add, GUI / Visual, JS / Technical, Test & Merge

#94 Tracking details on Manga Details Modal
  site/img/trackers/ic_tracker_mal.webp
  site/img/trackers/ic_tracker_manga_updates.webp
  site/index.html
  site/scripts/constants.js
  site/scripts/library.js
  site/styles/manga-details.css
Labels: Test & Merge
