Repository Animeboynz/Mihon-Backup-Viewer, pull requests merged in 2024-06, with the labels that each got.

#23 Use the `mangaThumbnail` as background for `manga-header`.
  index.html
  script.js
  styles.css
Labels: Enhancement, GUI / Visual

#30 Adds a `Settings Icon`
  index.html
  script.js
  styles.css
Labels: Feature to Add

#52 Fix error when backups have no backupCategories
  script.js
Labels: Bug, JS / Technical, High Priority
